import type { NextPage } from "next";
import Head from "next/head";
import Login from "../components/Login";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Next-Firebase-Crud</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Login />
      <i className="fa-sharp fa-solid fa-user"></i>
    </div>
  );
};

export default Home;
